version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/mobx-changeset-validations
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependecies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      - run:
          name: test
          command: yarn test



